### ISSUE TITLE
css 清除浮动

### ISSUE THREAD

**Issue by txlwll** [txlwll/css_note#1]
### 方法一：添加新的元素 、应用 clear：both；
```html
<div class="outer">
        <div class="div1">1</div>
        <div class="div2">2</div>
        <div class="div3">3</div>
        <div class="clear"></div>
    </div>
```

```css
.outer,.outer-third {
    border: 1px solid #ccc;
    background: #fc9;
    color: #fff;
    margin: 50px auto;
    padding: 50px;
}

.div1 {
    width: 80px;
    height: 80px;
    background: red;
    float: left;
}

.div2 {
    width: 80px;
    height: 80px;
    background: blue;
    float: left;
}

.div3 {
    width: 80px;
    height: 80px;
    background: sienna;
    float: left;
}

.clear {
    clear: both;
    height: 0;
    line-height: 0;
    font-size: 0
}
```
### 方法二：父级div定义 overflow: auto

```html
   <div class="outer over-flow">
        <div class="div1">1</div>
        <div class="div2">2</div>
        <div class="div3">3</div>
    </div>
```
```css
.over-flow {
    overflow: auto;
    zoom: 1;
}
```
### 方法三：在浮动元素的父元素::after方法
```html
<div class="outer-third">
    <div class="div1">1</div>
    <div class="div2">2</div>
    <div class="div3">3</div>
</div>
```
```css
.outer-third::after {
    clear: both;
    content: '.';
    display: block;
    height: 0;
    visibility: hidden;
}
.outer-third {
    zoom: 1;
}
```
